# Generated by Django 4.2.26 on 2026-09-07 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_existing_tasks_to_legacy_projects(apps, schema_editor):
    """Create per-client legacy projects and assign existing tasks to them."""
    Project = apps.get_model("core", "Project")
    Task = apps.get_model("core", "Task")
    for task in Task.objects.filter(project__isnull=True).select_related("client"):
        project, _ = Project.objects.get_or_create(
            client_id=task.client_id,
            name="Legacy project",
            defaults={"description": "Tasks created before project support."},
        )
        task.project_id = project.id
        task.save(update_fields=["project"])


def reverse_legacy_project_assignment(apps, schema_editor):
    """Remove project assignments before reversing the schema migration."""
    Task = apps.get_model("core", "Task")
    Task.objects.update(project=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name that identifies the project.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional context about the project.",
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the project was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the project was last changed.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client user who owns this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ("-updated_at", "name"),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                help_text="The project containing this task.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.project",
                verbose_name="project",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="unique_project_name_per_client"
            ),
        ),
        migrations.RunPython(
            assign_existing_tasks_to_legacy_projects,
            reverse_legacy_project_assignment,
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                help_text="The project containing this task.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.project",
                verbose_name="project",
            ),
        ),
    ]
