# Generated by Django 4.2.26 on 2026-09-08 00:51

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_task_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Rich-text context and notes for the task.",
                verbose_name="description",
            ),
        ),
    ]
