# Generated by Django 4.2.26 on 2026-09-09 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_task_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this client currently has project access.",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When project access was granted.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project shared with this client.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The client who accepted access to this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
            ],
            options={
                "verbose_name": "project membership",
                "verbose_name_plural": "project memberships",
            },
        ),
        migrations.CreateModel(
            name="ProjectInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The opaque single-use invitation identifier.",
                        unique=True,
                        verbose_name="invitation token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="The current invitation lifecycle state.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this invitation was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitee accepted this invitation.",
                        null=True,
                        verbose_name="accepted at",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        help_text="The client who may accept this invitation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_project_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invitee",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        help_text="The project owner who sent this invitation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_project_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inviter",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this invitation grants access to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project invitation",
                "verbose_name_plural": "project invitations",
            },
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("project", "invitee"),
                name="unique_pending_project_invitation",
            ),
        ),
    ]
